import type { Metadata } from "next";
import { Libre_Baskerville, Geist_Mono } from "next/font/google"; 
import "./globals.css";

const libreBaskervilleItalic = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400"], 
  style: ["italic"],
  variable: "--font-libre-baskerville-italic", 
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libreBaskervilleItalic.variable} ${geistMono.variable} antialiased`}
        
      >
        {children}
      </body>
    </html>
  );
}